# Generated by Django 5.0.7 on 2024-11-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Biography', 'Biography'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Comics', 'Comics'), ('Kids_Book', 'Kids_Book'), ('History', 'History'), ('Horror', 'Horror'), ('Finannce', 'Finance'), ('Science', 'Science'), ('Self-Help', 'Self-Help')], max_length=50),
        ),
    ]
